steps:
  # Build the backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sgi-backend', './backend']
    id: 'backend'

  # Build the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sgi-frontend', './frontend']
    id: 'frontend'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sgi-backend']
    waitFor: ['backend']

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sgi-frontend']
    waitFor: ['frontend']

images:
  - 'gcr.io/$PROJECT_ID/sgi-backend'
  - 'gcr.io/$PROJECT_ID/sgi-frontend'
